FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --frozen-lockfile

COPY . .

RUN npm run build
FROM node:18-alpine AS runner

WORKDIR /app
COPY --from=builder /app/package.json ./
COPY --from=builder /app/.next .next
COPY --from=builder /app/public ./public
RUN npm install --omit=dev --frozen-lockfile
EXPOSE 3000
CMD ["npm", "run", "start"]
